#!/usr/bin/env python3
"""
Documentacion del endpoint de reporte de reservas de proveedores
"""

def mostrar_documentacion():
    """Muestra la documentacion completa del endpoint"""
    
    print("=" * 80)
    print("REPORTE DE RESERVAS DE PROVEEDORES - DOCUMENTACION")
    print("=" * 80)
    print()
    
    print("INFORMACION DEL ENDPOINT:")
    print("-" * 40)
    print("URL: GET /api/v1/admin/reports/reservas-proveedores")
    print("Descripcion: Genera reporte detallado de reservas de proveedores")
    print("Permisos: Solo administradores")
    print("Autenticacion: Bearer Token requerido")
    print()
    
    print("DATOS INCLUIDOS EN EL REPORTE:")
    print("-" * 40)
    print("Cliente:")
    print("   - Nombre completo")
    print("   - Email de contacto (desde auth.users)")
    print("   - User ID")
    print()
    print("Proveedor:")
    print("   - Razon social de la empresa")
    print("   - Nombre fantasia")
    print("   - ID del usuario proveedor")
    print()
    print("Servicio:")
    print("   - Nombre del servicio")
    print("   - Precio del servicio")
    print("   - Descripcion del servicio")
    print("   - Categoria del servicio")
    print()
    print("Reserva:")
    print("   - Fecha del servicio")
    print("   - Horario (inicio - fin)")
    print("   - Fecha de creacion de la reserva")
    print("   - Descripcion de la reserva")
    print("   - Observaciones")
    print()
    print("Estado:")
    print("   - Valor del estado (pendiente, aprobado, etc.)")
    print("   - Etiqueta formateada")
    print("   - Color para UI")
    print()
    
    print("ESTADISTICAS INCLUIDAS:")
    print("-" * 40)
    print("• Total de reservas")
    print("• Conteo por estado")
    print("• Total de proveedores unicos")
    print("• Total de clientes unicos")
    print("• Fecha de generacion del reporte")
    print()
    
    print("EJEMPLO DE USO:")
    print("-" * 40)
    print("// En el frontend (AdminDashboardPage)")
    print("const obtenerReporteReservas = async () => {")
    print("  try {")
    print("    const response = await fetch('/api/v1/admin/reports/reservas-proveedores', {")
    print("      headers: {")
    print("        'Authorization': `Bearer ${user.accessToken}`, ")
    print("        'Content-Type': 'application/json'")
    print("      }")
    print("    });")
    print("    ")
    print("    if (response.ok) {")
    print("      const data = await response.json();")
    print("      console.log('Total reservas:', data.total_reservas);")
    print("      console.log('Reservas:', data.reservas);")
    print("      console.log('Estadisticas:', data.estadisticas);")
    print("    }")
    print("  } catch (error) {")
    print("    console.error('Error:', error);")
    print("  }")
    print("};")
    print()
    
    print("ESTRUCTURA DE RESPUESTA:")
    print("-" * 40)
    print("{")
    print('  "total_reservas": 25,')
    print('  "reservas": [')
    print('    {')
    print('      "id_reserva": 123,')
    print('      "cliente": {')
    print('        "nombre": "Juan Perez",')
    print('        "email": "juan@email.com",')
    print('        "user_id": "uuid-del-cliente"')
    print('      },')
    print('      "proveedor": {')
    print('        "empresa": "Empresa ABC S.A.",')
    print('        "nombre_fantasia": "ABC Servicios",')
    print('        "user_id": "uuid-del-proveedor"')
    print('      },')
    print('      "servicio": {')
    print('        "nombre": "Limpieza de oficinas",')
    print('        "precio": 150.00,')
    print('        "descripcion": "Servicio de limpieza...",')
    print('        "categoria": "Limpieza"')
    print('      },')
    print('      "reserva": {')
    print('        "fecha_servicio": "15/12/2024",')
    print('        "horario": "09:00 - 17:00",')
    print('        "fecha_reserva": "10/12/2024 14:30",')
    print('        "descripcion": "Limpieza general...",')
    print('        "observacion": "Acceso por puerta principal"')
    print('      },')
    print('      "estado": {')
    print('        "valor": "aprobado",')
    print('        "label": "Aprobado",')
    print('        "color": "green"')
    print('      }')
    print('    }')
    print('  ],')
    print('  "estadisticas": {')
    print('    "por_estado": {')
    print('      "pendiente": 5,')
    print('      "aprobado": 15,')
    print('      "rechazado": 3,')
    print('      "concluido": 2')
    print('    },')
    print('    "total_proveedores": 8,')
    print('    "total_clientes": 12')
    print('  },')
    print('  "fecha_generacion": "2024-12-06T10:30:00",')
    print('  "filtros_aplicados": "Todas las reservas de proveedores"')
    print('}')
    print()
    
    print("INTEGRACION EN EL FRONTEND:")
    print("-" * 40)
    print("1. Agregar boton en AdminDashboardPage")
    print("2. Crear modal o pagina para mostrar el reporte")
    print("3. Implementar tabla con datos de reservas")
    print("4. Mostrar estadisticas en tarjetas")
    print("5. Agregar filtros por estado, fecha, proveedor")
    print("6. Implementar exportacion a CSV/Excel")
    print()
    
    print("FILTROS FUTUROS (OPCIONAL):")
    print("-" * 40)
    print("• Por rango de fechas")
    print("• Por estado de reserva")
    print("• Por proveedor especifico")
    print("• Por cliente especifico")
    print("• Por categoria de servicio")
    print("• Por rango de precios")
    print()
    
    print("VENTAJAS DEL ENDPOINT:")
    print("-" * 40)
    print("• Informacion completa en una sola consulta")
    print("• Datos estructurados y formateados")
    print("• Estadisticas automaticas")
    print("• Optimizado para reportes administrativos")
    print("• Facil integracion con frontend")
    print("• Preparado para exportacion")
    print()
    
    print("=" * 80)
    print("DOCUMENTACION COMPLETADA")
    print("=" * 80)

if __name__ == "__main__":
    mostrar_documentacion()
